function writeCalibrationData(subjectNumber, gazeCalibLogFD, accuracyStruct)
  calibrationData = sprintf('%f,%f,%f,%f', accuracyStruct.deviationLX,... 
                            accuracyStruct.deviationLY,... 
                            accuracyStruct.deviationRX,... 
                            accuracyStruct.deviationRY);
  fprintf(gazeCalibLogFD, '%d,%s\r\n', subjectNumber, calibrationData);
  return
